name: MotherDuck Integration Test

on: [push, pull_request]

jobs:
  test-motherduck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Ensure this matches your project's requirements

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install duckdb  # Install the duckdb package

    - name: Run MotherDuck Test
      env:
        MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
      run: python ./tests/motherduck_test.py
